name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: PADAS/gundi-workflows/.github/workflows/pipeline-dispatcher-docker-main.yml@main
    secrets: inherit
    with:
      secret_name: "wps-dispatcher-defaults"
      environment: dev