name: Build dispatcher
on:
  push:
    branches:
      - main

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi-dispatchers/wpswatch" >> $GITHUB_OUTPUT

  run_unit_tests:
    runs-on: ubuntu-latest
    needs: [vars]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install pip
        run: python -m ensurepip --upgrade
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.in
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Install dev dependencies
        run: pip install -r requirements-dev.in
      - name: Run unit tests
        run: pytest
        env:
          TRACING_ENABLED: False
  
  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v2
    needs: [vars,run_unit_tests]
    with:
      environment: dev
      repository: ${{ needs.vars.outputs.repository }}
      tag: ${{ needs.vars.outputs.tag }}
      dockerfile: Dockerfile
