name: Pull Request Workflow

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  pr:
    uses: PADAS/gundi-workflows/.github/workflows/pipeline-dispatcher-docker-pr.yml@main
    secrets: inherit