name: Release Workflow

on:
  push:
    branches:
      - 'release-**'

jobs:
  release:
    uses: PADAS/gundi-workflows/.github/workflows/pipeline-dispatcher-docker-release.yml@main
    secrets: inherit
    with:
      secret_name: "wps-dispatcher-defaults-dev"
      stage_environment: stage
      prod_environment: prod